### ISSUE TITLE
VM Extension provisioning error

### ISSUE THREAD

**Issue by araskal** [dmauser/opnazure#14]
"message": "VM has reported a failure when processing extension 'CustomScript'. Error message: \"Script returned an error.\n---stdout---\nUpdating FreeBSD repository catalogue...\nFetching meta.txz: . done\nrepository FreeBSD has no meta file, using default settings\nFetching packagesite.txz: .......... done\nUnable to open created repository FreeBSD\nUnable to update repository FreeBSD\nError updating repositories!\n\nBinding static ARP pair(s): azvip.\n\n---errout---\nconfig-snic.xml                                         24 kB 4613 kBps    00s\npkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2\npkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2\npkg: Repository FreeBSD load error: meta cannot be loaded No error: 0\nfetch: https://raw.githubusercontent.com/opnsense/update/master/bootstrap/opnsense-bootstrap.sh.in: Not Found\nsed: opnsense-bootstrap.sh.in: No such file or directory\nsh: cannot open ./opnsense-bootstrap.sh.in: No such file or directory\nlb-conf.sh                                             386  B 7865 kBps    00s\n./lb-conf.sh: cannot create /usr/local/etc/rc.syshook.d/start/20-freebsd: No such file or directory\n\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot "

error received when deploying single-nic instance in existing vnet

**Comment by dmauser** [comment]
Thanks for the heads up. It has been fixed. Let me know if you can try deploying it again and works.

**Comment by dmauser** [comment]
It has been fixed
