### ISSUE TITLE
Error on deploy VM

### ISSUE THREAD

**Issue by garria** [dmauser/opnazure#18]
Hello,
could you please verify why the postinstall VM script failed with this error?

{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'CustomScript'. Error message: \\\"Script returned an error.\\n---stdout---\\nIGNORE_OSVERSION=yes\\nAZURE_GUEST_AGENT_EXTENSION_PATH=/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0\\nConfigSequenceNumber=0\\nPATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin\\nPWD=/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/download/0\\nAZURE_GUEST_AGENT_EXTENSION_SUPPORTED_FEATURES=[{\\\"Value\\\": \\\"1.0\\\", \\\"Key\\\": \\\"ExtensionTelemetryPipeline\\\"}]\\nHOME=/\\nAZURE_GUEST_AGENT_EXTENSION_VERSION=1.4.1.0\\nAZURE_GUEST_AGENT_WIRE_PROTOCOL_ADDRESS=168.63.129.16\\nAZURE_GUEST_AGENT_UNINSTALL_CMD_EXIT_CODE=NOT_RUN\\nRC_PID=23\\nUpdating FreeBSD repository catalogue...\\nFetching meta.txz: . done\\nrepository FreeBSD has no meta file, using default settings\\nFetching packagesite.txz: .......... done\\nUnable to open created repository FreeBSD\\nUnable to update repository FreeBSD\\nError updating repositories!\\nUpdating FreeBSD repository catalogue...\\nFetching meta.txz: . done\\nrepository FreeBSD has no meta file, using default settings\\nFetching packagesite.txz: .......... done\\nUnable to open created repository FreeBSD\\nUnable to update repository FreeBSD\\nError updating repositories!\\n\\nBinding static ARP pair(s): azvip.\\n\\n---errout---\\n_config_dependencies.xml\\nx WALinuxAgent-2.4.0.2/tests/data/wire/remote_access_10_accounts.xml\\nx WALinuxAgent-2.4.0.2/tests/data/wire/remote_access_duplicate_accounts.xml\\nx WALinuxAgent-2.4.0.2/tests/data/wire/remote_access_no_accounts.xml\\nx WALinuxAgent-2.4.0.2/tests/data/wire/remote_access_single_account.xml\\nx WALinuxAgent-2.4.0.2/tests/data/wire/remote_access_two_accounts.xml\\nx WALinuxAgent-2.4.0.2/tests/data/wire/sample.pem\\nx WALinuxAgent-2.4.0.2/tests/data/wire/shared_config.xml\\nx WALinuxAgent-2.4.0.2/tests/data/wire/sshd_config\\nx WALinuxAgent-2.4.0.2/tests/data/wire/trans_cert\\nx WALinuxAgent-2.4.0.2/tests/data/wire/trans_prv\\nx WALinuxAgent-2.4.0.2/tests/data/wire/trans_pub\\nx WALinuxAgent-2.4.0.2/tests/data/wire/version_info.xml\\nx WALinuxAgent-2.4.0.2/tests/distro/\\nx WALinuxAgent-2.4.0.2/tests/distro/__init__.py\\nx WALinuxAgent-2.4.0.2/tests/distro/test_resourceDisk.py\\nx WALinuxAgent-2.4.0.2/tests/distro/test_scvmm.py\\nx WALinuxAgent-2.4.0.2/tests/ga/\\nx WALinuxAgent-2.4.0.2/tests/ga/__init__.py\\nx WALinuxAgent-2.4.0.2/tests/ga/extension_emulator.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_collect_logs.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_collect_telemetry_events.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_env.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_extension.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_exthandlers.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_exthandlers_download_extension.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_exthandlers_exthandlerinstance.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_monitor.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_multi_config_extension.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_periodic_operation.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_remoteaccess.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_remoteaccess_handler.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_send_telemetry_events.py\\nx WALinuxAgent-2.4.0.2/tests/ga/test_update.py\\nx WALinuxAgent-2.4.0.2/tests/pa/\\nx WALinuxAgent-2.4.0.2/tests/pa/__init__.py\\nx WALinuxAgent-2.4.0.2/tests/pa/test_deprovision.py\\nx WALinuxAgent-2.4.0.2/tests/pa/test_provision.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/\\nx WALinuxAgent-2.4.0.2/tests/protocol/__init__.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/mocks.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/mockwiredata.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/test_datacontract.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/test_healthservice.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/test_hostplugin.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/test_image_info_matcher.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/test_imds.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/test_metadata_server_migration_util.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/test_protocol_util.py\\nx WALinuxAgent-2.4.0.2/tests/protocol/test_wire.py\\nx WALinuxAgent-2.4.0.2/tests/test_agent.py\\nx WALinuxAgent-2.4.0.2/tests/tools.py\\nx WALinuxAgent-2.4.0.2/tests/utils/\\nx WALinuxAgent-2.4.0.2/tests/utils/__init__.py\\nx WALinuxAgent-2.4.0.2/tests/utils/cgroups_tools.py\\nx WALinuxAgent-2.4.0.2/tests/utils/event_logger_tools.py\\nx WALinuxAgent-2.4.0.2/tests/utils/miscellaneous_tools.py\\nx WALinuxAgent-2.4.0.2/tests/utils/test_archive.py\\nx WALinuxAgent-2.4.0.2/tests/utils/test_crypt_util.py\\nx WALinuxAgent-2.4.0.2/tests/utils/test_extension_process_util.py\\nx WALinuxAgent-2.4.0.2/tests/utils/test_file_util.py\\nx WALinuxAgent-2.4.0.2/tests/utils/test_flexible_version.py\\nx WALinuxAgent-2.4.0.2/tests/utils/test_network_util.py\\nx WALinuxAgent-2.4.0.2/tests/utils/test_passwords.txt\\nx WALinuxAgent-2.4.0.2/tests/utils/test_rest_util.py\\nx WALinuxAgent-2.4.0.2/tests/utils/test_shell_util.py\\nx WALinuxAgent-2.4.0.2/tests/utils/test_text_util.py\\nconfigureopnsense.sh: python3: not found\\nactions_waagent.conf                                   357  B 6441 kBps    00s\\ncp: /usr/local/opnsense/service/conf/actions.d: No such file or directory\\nconfigureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/22-remoteroute: No such file or directory\\nchmod: /usr/local/etc/rc.syshook.d/start/22-remoteroute: No such file or directory\\nconfigureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/20-freebsd: No such file or directory\\n\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}

Thank you.
Regards.
Gianluca A.

**Comment by dmauser** [comment]
Thanks for reporting this issue. It looks like Azure VM agent is not working properly on the latest OPNSense version. @Welasco can you take a look on that issue reported above please?

**Comment by Welasco** [comment]
@dmauser, @garria problem fixed.

OPNsense updated their bootstrap image to require FreeBSD version 13.
For now I revert their change to 12 since we don't have an official Microsoft image for FreeBSD 13 yet.

I'll work on it trying to use a third party image to keep it in the latest version.

For now it's using FreeBSD 12 and OPNsense 21.7.

I'll work upgrading to FreeBSD 13 and OPNsense 22.1 as soon as possible.
