### ISSUE TITLE
Azure Backup/Snapshot support

### ISSUE THREAD

**Issue by flaviomeyer** [dmauser/opnazure#2]
Good Morning @dmauser 

Currently there is a problem with the Azure Backup which does not work.
Specifically, Microsoft does not yet support FreeBSD.

The problem can be solved in the meantime by installing Bash.

> Information from Microsoft Support:
> I have received feedback from our Product Team and we will soon be announcing “preview for FreeBSD Support”.
> In order to get the backup working we should install bash shell in the VM, please try and deploy a new backup to confirm if that was successful.
>  
> Steps to install bash-
> pkg update
> pkg upgrade
> pkg install bash

Of course, it would be great if Azure Backup support is available after installation without manual intervention by the end user of OPNsense on Microsoft Azure infrastructure.

**Comment by dmauser** [comment]
Thanks for the feedback.  I can incorporate those steps inside the automation configuration script.
I will work on it and let you know when I have an update.

**Comment by dmauser** [comment]
> Good Morning @dmauser
> 
> Currently there is a problem with the Azure Backup which does not work.
> Specifically, Microsoft does not yet support FreeBSD.
> 
> The problem can be solved in the meantime by installing Bash.
> 
> > Information from Microsoft Support:
> > I have received feedback from our Product Team and we will soon be announcing “preview for FreeBSD Support”.
> > In order to get the backup working we should install bash shell in the VM, please try and deploy a new backup to confirm if that was successful.
> > Steps to install bash-
> > pkg update
> > pkg upgrade
> > pkg install bash
> 
> Of course, it would be great if Azure Backup support is available after installation without manual intervention by the end user of OPNsense on Microsoft Azure infrastructure.

I see installation will take very long by incorporating pkg update + pkg upgrade. It would add probably few more minutes to the installation process. On a new install when I jut run pkg install bash it gets version 5.0.11 installed. Adding only pkg install bash only would not increase the installation process. Therefore, I will add only **pkg install bash** to the installation process. Let me know if that is enough or you really need to have pkg update + pkg upgrade as well.

**Comment by Welasco** [comment]
Closing. Assuming it was fixed after installing bash.
