### ISSUE TITLE
Azure agent does not work in version OPNsense 22.7.2-amd64

### ISSUE THREAD

**Issue by garria** [dmauser/opnazure#35]
Hello,
after I upgraded the version of opnsense to 22.7.2 the Azure agent does not work due this error:
 Starting waagent.
env: python: No such file or directory
/etc/rc.d/waagent: WARNING: failed to start waagent
Thank you.
Regards,
Gianluca A.

**Comment by cjnova** [comment]
Hello,
this is because python version was upgraded from 3.8 to 3.9. If you want ot remediate manually you can do it with these steps:

- Login with SSH
- Remove non-working alias: `rm /usr/local/bin/python`
- Create right alias to pythoon 3.9: `ln -s /usr/local/bin/python3.9 /usr/local/bin/python`

Regards,

**Comment by Welasco** [comment]
Thank you both (@garria and @cjnova). I'll work on a fix ASAP and let you guys know.

**Comment by cjnova** [comment]
I requested a PR to solve this. Also deploying 22.7 version and latest agent version. I have prepared another PR ready to deploy OPNSense on top of FreeBSD 13.1

**Comment by Welasco** [comment]
@cjnova, I'll check the PR now then. Really appreciate for helping us here.

**Comment by Welasco** [comment]
The PR is merged. I'll fix test the workflow now.

**Comment by Welasco** [comment]
Just an update, the code was merged but the Click to deploy will only work after the test run. I'll work on it and let you guys know when it's done.

**Comment by Welasco** [comment]
All working now!
@cjnova, once again tks for your contribution.

Just something I noticed, after the deployment the FreeBSD version was 13.1 already. We are using the official FreeBSD base image published on Azure from FreeBSD organization, I believe after update to the latest version of OPNSense bootstrap script it also updated it from 13.0 to 13.1.

**Comment by cjnova** [comment]
Interesting. In my tests, you can check my fork cjnova/opnazure dev branch, it works with freebsd 13.0. I have also prepared other modifications to bicep files where I'm referencing freebsd 13.1 as base image, also updated API references (vm resource) to latest ones. I am going to create another PR for bicep. Also it worth to mention in documentation that you should allow (accept terms) freebsd images, or your deployment will fail.

for example:

## Accepting FreeBSD terms with PowerShell

From a Powershell console with Azure subscriptions access:

`Get-AzMarketplaceTerms -Publisher 'thefreebsdfoundation' -Product 'freebsd-13_1' -Name '13_1-release' | Set-AzMarketplaceTerms -Accept`

## Accepting FreeBSD terms with Az Cli

`az vm image terms accept --urn thefreebsdfoundation:freebsd-13_0:13_0-release:latest`
