### ISSUE TITLE
The HTTP_REFERER does not match the predefined settings

### ISSUE THREAD

**Issue by DennisGaida** [dmauser/opnazure#49]
Using the single NIC image after having accepted the license terms. Deployment works flawlessly (nice!).

After loading `https://<public-ip>` (doesn't work in edge due to invalid cert authority, firefox works with errors), I login via root:opnsense. Right after that I get the error:

```
The HTTP_REFERER "https://<public-ip>/" does not match the predefined settings. You can disable this check if needed under System: Settings: Administration.
```

I believe this might be fixed with `<nodnsrebindcheck>1</nodnsrebindcheck>` in https://github.com/dmauser/opnazure/blob/master/scripts/config.xml.

Unfortunately it is not easy for me to debug since with the SingleNic I can't connect via SSH (seems blocked) and I didn't want to go through the setup again with two NICs and a jumphost.

**Comment by dmauser** [comment]
For now we are recommending using the TwoNiC scenario (the most popular) because we're discontinuing the single NIC support. 
CCing @Welasco  as FYI.

**Comment by Welasco** [comment]
As @dmauser mentioned, I just took this option out to avoid further problems. You can achieve everything using TwoNIC scenario.
