### ISSUE TITLE
Cant reach internet from vm in spoke

### ISSUE THREAD

**Issue by sergioaten** [dmauser/opnazure#54]
Hi!

I will describe my scenario.

I have vnet hub with 10.0.0.0/24 address space with OPNSense twonics configured.
I have vnet spoke with 10.1.0.0/24 address space with a vm to do tests.
I configured rules to allow the traffic from the spoke in LAN and WAN interface.

In the subnet spoke, i have an UDR which have a route with 0.0.0.0/0 to OPNsense trusted NIC IP how you explain in the documentation.
But my vm in the spoke to test cant reach internet.

The traffic reach to the firewall, but doesnt comes to reply the vm.
![Screenshot fw.](https://i.imgur.com/HxoUg8u.png)

I guess i have some problem with routing, but idk what.

Regards.

**Comment by dmauser** [comment]
Did you set up a NAT - Outbound Rule on the OPNSense?
https://docs.opnsense.org/manual/nat.html#outbound

**Comment by sergioaten** [comment]
yes, that was it. I configured it 3 hours ago and its working.

Regards!
