### ISSUE TITLE
Deployment fails - InvalidTemplate

### ISSUE THREAD

**Issue by Jacox98** [dmauser/opnazure#60]
Hi

When trying deploy this on Azure, the deployment failed on the CustomScript part on the created VM.

anybody have a solutions for this ?

{
  "code": "InvalidTemplate",
  "message": "Unable to process template language expressions for resource '/subscriptions/xxxxxxxx/xxxxxxxx/xxxxxx/providers/Microsoft.Compute/virtualMachines/OPNsense/extensions/CustomScript' at line '1' and column '4289'. 'The language expression property 'addressPrefix' doesn't exist, available properties are 'provisioningState, addressPrefixes, delegations, privateEndpointNetworkPolicies, privateLinkServiceNetworkPolicies'.'",
  "additionalInfo": [
    {
      "type": "TemplateViolation",
      "info": {
        "lineNumber": 1,
        "linePosition": 4289,
        "path": ""
      }
    }
  ]
}

**Comment by dmauser** [comment]
@Jacox98, thanks for the heads up.
I have fixed the deployment issue. Can you redeployment and let us know?

**Comment by emmanuelpare** [comment]
Hi @dmauser  I just tested and it work perfectly!  Good Job

**Comment by dmauser** [comment]
Confirmed deployment issued has been fixed. Closing issue.
