### ISSUE TITLE
Deployment fail - invalid template custom script

### ISSUE THREAD

**Issue by AndreySinenok** [dmauser/opnazure#61]
Hi, I have a problem similar to https://github.com/dmauser/opnazure/issues/60 but on a different line, what can I do to fix this problem?
{
  "code": "InvalidTemplate",
  "message": "Unable to process template language expressions for resource '/subscriptions/07de39e7-6993-4604-acac-bd3ce428551d/resourceGroups/rg-network-backbone/providers/Microsoft.Compute/virtualMachines/OPNsense/extensions/CustomScript' at line '1' and column '4319'. 'The language expression property 'addressPrefix' doesn't exist, available properties are 'provisioningState, addressPrefixes, ipConfigurations, delegations, privateEndpointNetworkPolicies, privateLinkServiceNetworkPolicies'.'",
  "additionalInfo": [
    {
      "type": "TemplateViolation",
      "info": {
        "lineNumber": 1,
        "linePosition": 4319,
        "path": ""
      }
    }
  ]
}

**Comment by Welasco** [comment]
I'm checking it now.

**Comment by Welasco** [comment]
I believe the problem was related to WA Linux agent version.
I just updated to the latest version 2.11.1.4

You can try to deploy again like this:

![image](https://github.com/dmauser/opnazure/assets/26201510/cd576d76-b756-4c69-9baa-16d66531acba)

This issue will be closed once the PR is merged.
