### ISSUE TITLE
Deployment Failed when using Existing VNet

### ISSUE THREAD

**Issue by zaubergulasch** [dmauser/opnazure#65]
The Deployment Failed when using an existing vnet, the vnet was not found in the newly created resource group.

BR

Tim

**Comment by dmauser** [comment]
@zaubergulasch, thanks for the heads up. I am investigating that behavior.

**Comment by dmauser** [comment]
@zaubergulasch this issue has been resolved. I am closing this issue. Thanks again for reporting this issue.
